### ISSUE TITLE
Doesn't save arenas

### ISSUE THREAD

**Issue by KohlrabitoDev** [jakeryang/SimplePaintball#3]
The plugin doesn't save arenas to a file. Could you make it do that? Maybe even add MySQL as well? Thanks!

**Comment by jakegut** [comment]
Were the arenas activated? And did you do a reload server after you created an arena?

**Comment by KohlrabitoDev** [comment]
Yes and yes, I've done both. I don't see a file generated for it. I see player_stats.db

**Comment by KohlrabitoDev** [comment]
Just reloaded the plugin and it actually deleted the arenas out of memory completely.

**Comment by jakegut** [comment]
Arenas are stored in config.yml (which is a bad idea I know) and should be under 'arenas'. I would double check that they're under there. The only reason that I can think of right now is that the arenas weren't activated when you reloaded the server. And there is some unexpected things about arenas saving and loading when reload is used. I'll look into it further in the next one or two days or so.

**Comment by jakegut** [comment]
In one of the latest releases, arenas now save in a separate file. A recent commit added a /pb save feature to force save arenas. The command will only save activated arenas. I'm closing this. Errors or other features can be made in another issue
